webtalk_init -webtalk_dir D:\\Nora\\cmod_a7_projects\\microblaze_led\\microblaze_led.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2016-11-15 21:02:40" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "p460pm3p76jgcs8ll50pd7jg3d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.3_10" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4008 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1479131577088" -context "sdk\\\\bsp/1479131577088"
webtalk_add_data -client sdk -key hwid -value "1478787065467" -context "sdk\\\\bsp/1479131577088"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1479131577088"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\bsp/1479131577088"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1479131577088"
webtalk_add_data -client sdk -key uid -value "1479131577808" -context "sdk\\\\application/1479131577808"
webtalk_add_data -client sdk -key hwid -value "1478787065467" -context "sdk\\\\application/1479131577808"
webtalk_add_data -client sdk -key bspid -value "1479131577088" -context "sdk\\\\application/1479131577808"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1479131577808"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1479131577808"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\application/1479131577808"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1479131577808"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1479131577808"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1479131577808"
webtalk_add_data -client sdk -key projSize -value "312.6962890625" -context "sdk\\\\application/1479131577808"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1479236560545"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1479236560545"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1479236560545"
webtalk_add_data -client sdk -key DebugCount -value "71" -context "sdk\\\\bsp/1479236560545"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1479236560545"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1479236560545"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1479236560545"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1479236560545"
webtalk_transmit -clientid 2385332419 -regid "" -xml D:\\Nora\\cmod_a7_projects\\microblaze_led\\microblaze_led.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\Nora\\cmod_a7_projects\\microblaze_led\\microblaze_led.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\Nora\\cmod_a7_projects\\microblaze_led\\microblaze_led.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
